// This file is auto-generated and will be over-written!
// Please do NOT edit this file directly
// You may edit that file instead: src\lib\css\styles.css

export const styles = `
#selector text {
  font-size: 16px;
  font-family: Open Sans, sans-serif;
}

#selector text.title {
  font-size: 24px;
  font-weight: 500;
}

#selector text.subTitle {
  font-weight: 500;
  fill: #777777;
}

#selector text.caption {
  font-weight: 400;
  font-size: 24px;
  fill: #777777;
}

#selector text.label {
  font-weight: 600;
}

#selector text.valueLabel {
  font-weight: 300;
}

#selector text.dateCounterText {
  font-size: 64px;
  font-weight: 700;
  opacity: 0.25;
}

#selector .tick text {
  fill: #777777;
}

#selector .xAxis .tick:nth-child(2) text {
  text-anchor: start;
}

#selector .tick line {
  shape-rendering: CrispEdges;
  stroke: #dddddd;
}

#selector .tick line.origin {
  stroke: #aaaaaa;
}

#selector path.domain {
  display: none;
}

#selector {
  position: relative;
}

#selector .controls {
  /*  width and right are set dynamically in renderer.ts */
  position: absolute;
  top: 0;
  display: flex;
}

#selector .controls div,
#selector .overlay div {
  cursor: pointer;
  font-size: 24px;
  font-weight: 700;
  width: 38px;
  height: 38px;
  color: #ffffff;
  background: #777777;
  border: 1px solid black;
  opacity: 0.5;
  -moz-border-radius: 5px;
  -webkit-border-radius: 5px;
  border-radius: 5px;
  margin: 5px;
  text-align: center;
}

#selector .controls div:hover,
#selector .overlay div:hover {
  background: #aaaaaa;
  color: black;
}

#selector .controls svg {
  margin: 5px auto;
  width: 28px;
  height: 28px;
}

#selector .overlay {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: black;
  opacity: 0.7;
  display: flex;
  align-items: center;
  justify-content: center;
}
#selector .overlay div {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 200px;
  height: 200px;
  -moz-border-radius: 100px;
  -webkit-border-radius: 100px;
  border-radius: 100px;
}
#selector .overlay svg {
  height: 50%;
  width: 50%;
}
`;
