const fs = require('fs');
const path = require('path');

const cssDir = path.resolve(__dirname, 'lib/css/');
const cssBaseFile = path.resolve(cssDir, 'styles.css');
const tsFile = path.resolve(__dirname, 'lib/styles/generated-styles.ts');

function css2ts() {
  const css = fs.readFileSync(cssBaseFile, 'utf8');

  let stylesContent = '// This file is auto-generated and will be over-written!\n';
  stylesContent += '// Please do NOT edit this file directly\n';
  stylesContent += '// You may edit files in this folder instead: ';
  stylesContent += path.relative('.', cssDir) + '\n\n';
  stylesContent += 'export const styles = `\n';
  stylesContent += css;
  stylesContent += '`;\n\n';

  stylesContent += 'export const themes = {\n';
  fs.readdirSync(cssDir).forEach((theme) => {
    if (theme.endsWith('.theme.css')) {
      const themeCss = fs.readFileSync(path.resolve(cssDir, theme), 'utf8');
      stylesContent += '"' + theme.split('.theme.css')[0] + '": `\n';
      stylesContent += themeCss;
      stylesContent += '`,\n';
    }
  });
  stylesContent += '};\n';

  fs.writeFileSync(tsFile, stylesContent);
}

css2ts();

if (process.argv[2] === '-w' || process.argv[2] === '--watch') {
  fs.watch(cssDir, css2ts);
}
