const fs = require('fs');
const path = require('path');

const cssFile = path.resolve(__dirname, 'lib/css/styles.css');
const tsFile = path.resolve(__dirname, 'lib/styles/styles.ts');

function css2ts() {
  const css = fs.readFileSync(cssFile, 'utf8');

  let stylesContent = '// This file is auto-generated and will be over-written!\n';
  stylesContent += '// Please do NOT edit this file directly\n';
  stylesContent += '// You may edit that file instead: ' + path.relative('.', cssFile) + '\n\n';
  stylesContent += 'export const styles = `\n';
  stylesContent += css;
  stylesContent += '`;\n';

  fs.writeFileSync(tsFile, stylesContent);
}

css2ts();

if (process.argv[2] == '-w' || process.argv[2] == '--watch') {
  fs.watchFile(cssFile, css2ts);
}
